### ISSUE TITLE
full screen toggle

### ISSUE THREAD

**Issue by ansarikhurshid786** [matinzd/rn-bottom-sheet#1]
how to toggle full screen and half screen and close it. 

can you suggestion something to achieve?

**Comment by matinzd** [comment]
> how to toggle full screen and half screen and close it.
> 
> can you suggestion something to achieve?

You can use these props in order to customize size of your bottom sheet

containerHeight
offset
downDisplay

**Comment by ansarikhurshid786** [comment]
i have done half and full screen. I stuck how to close it? 

I tried something like: 
`<BottomDrawer containerHeight={this.state.cHeight}> </BottomDrawer> `

dynamically changing height of container but it is not working.

**Comment by matinzd** [comment]
> i have done half and full screen. I stuck how to close it?
> 
> I tried something like:
> `<BottomDrawer containerHeight={this.state.cHeight}> </BottomDrawer> `
> 
> dynamically changing height of container but it is not working.

I will check.

**Comment by ansarikhurshid786** [comment]
have you check. because i am stuck since yesterday.

**Comment by ansarikhurshid786** [comment]
i can show and hide element base on condition but it is not smooth. 

can you create a function which close/hide bottomdrawer smoothly? like up and down position is very smooth... 

i have done as below :  
```
{ 
this.state.bottomState ? 
   <BottomDrawer containerHeight={Dimensions.get("window").height}> </BottomDrawer>
: 
null; 
}
```

**Comment by matinzd** [comment]
> i can show and hide element base on condition but it is not smooth.
> 
> can you create a function which close/hide bottomdrawer smoothly? like up and down position is very smooth...
> 
> i have done as below :
> 
> ```
> { 
> this.state.bottomState ? 
>    <BottomDrawer containerHeight={Dimensions.get("window").height}> </BottomDrawer>
> : 
> null; 
> }
> ```

You can use ` closeBottomDrawer()` to hide and set downDisplay to 0

**Comment by ansarikhurshid786** [comment]
@matinzd thanks let me try.

**Comment by ansarikhurshid786** [comment]
I tried but not working. have you tested? can you give me simple example

**Comment by ansarikhurshid786** [comment]
Not working as expecting. 

closeBottomDrawer() : 
If it is full screen then half and if half screen then nothing happen. 


I want close bottom drawer smoothly. 

can help me with some example?
